### ISSUE TITLE
wildcard filtering expression for sequences

### ISSUE THREAD

**Issue by iuhilnehc-ynos** [rticommunity/rmw_connextdds#11]
**Feature Description**

Content filtered topic feature in rti-connext-dds is excellent, especially supporting [arrys and sequences](https://community.rti.com/static/documentation/connext-dds/5.2.3/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_UsersManual/Content/UsersManual/SQL_Filter_Expression_Notation.htm#topics_3596570972_161086).

We decide to use this feature to filter data of ROS2 topics including "/parameter_events", "${concrete_action_name}/_action/feedback" and "${concrete_action_name}/_action/status", but we are experiencing a problem that is not filtering data for sequences of uncertain size and unknown item location.

For topic "/parameter_events", the publisher will publish data as following,

- ParameterEvent_.idl

```
    struct ParameterEvent {
      ...
      sequence<rcl_interfaces::msg::Parameter> new_parameters;
      ^^^^^^^^/\ the type of new_parameters is 'sequence'
      ...
    };
```

- data sample

```
stamp:
  sec: 1616464433
  nanosec: 595625771
node: /parameter_blackboard
new_parameters:                 # 1. sequence size is unknown for the subscriber,
                                # so we can't to use filter expression with
                                # "new_parameters[0].name.data MATCH 'use_sim_time' or ..."
- name: use_sim_time            # 2. the order of items for the 'name' is also uncertained,
                                # so we can't to use filter expression with
                                # "new_parameters[0].name.data MATCH 'use_sim_time'"
                                # e.g. if there are 10 items, 'use_sim_time' might be located on 7th, 9th, etc.
  value:
    type: 1
    bool_value: false
    integer_value: 0
    double_value: 0.0
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
changed_parameters: []
deleted_parameters: []
---
```

We can filter the node name with a filter expression "node MATCH '/parameter_blackboard'", but it seems there is no SQL grammar in rti-connext-dds to filter new_parameters with a specific name.

The publishers for topic "${concrete_action_name}/_action/status" are also publishing status data with uncertain size and index,
so we can't set the filter expression with a specific 'uuid' on the subscriber side.
 
```
status_list:             # uncertain size for 'goal_info'
- goal_info:
    goal_id:
      uuid:              # uncertain locatation(index) for 'uuid'.
      - 145
      - 2
      - 147
      - 138
      - 43
      - 172
      - 91
      - 12
      - 13
      - 111
      - 134
      - 245
      - 168
      - 79
      - 14
      - 191
    stamp:
      sec: 1616465176
      nanosec: 998640169
  status: 2

```

**Implementation Considerations**

I think it's a very useful feature to filter these data, do you plan to support the feature like wildcard filtering expression for sequences, such as "new_parameters[*].name MATCH 'use_sim_time'", "status_list[].goal_info.goal_id.uuid = &hex(%s)" or other non-number related statement.

NOTE: I'm sorry if it's not the correct place to post this feature request.
